### ISSUE TITLE
Add package to npm registry

### ISSUE THREAD

**Issue by Halleck45** [andyshora/grunt-yslow#1]
Hello,

The package seems not be registered by npm

```
npm install grunt-yslow
```

> npm ERR! 404 'grunt-yslow' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it

I don"t see the package when I search it manually on npmjs.org.

Could you add it to the npm registry ?

Thank's

**Comment by dpanov** [comment]
+1.

**Comment by andyshora** [comment]
Hey guys, I've added this to the npm registry under the package name grunt-yslow. It's pretty buggy at the moment, planning on a rewrite next week now that I'm better with Node!

**Comment by Halleck45** [comment]
Nice ! Thank's
