### ISSUE TITLE
`Files: [no src]` error

### ISSUE THREAD

**Issue by grega** [andyshora/grunt-yslow#2]
Using the config in your example:

```
yslow: {
  options: {
    thresholds: {
      weight: 180,
      speed: 1000,
      score: 80,
      requests: 15
    }
  },
  pages: {
    files: [
      {
        src: 'http://andyshora.com'
      },
      {
        src: 'http://www.google.co.uk',
        thresholds: {
          weight: 100
        }
      }
    ]
  }
},
```

I get the following output when running `grunt yslow -v`:

```
grunt yslow -v
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-yslow" local Npm module tasks.
Reading /node_modules/grunt-yslow/package.json...OK
Parsing /node_modules/grunt-yslow/package.json...OK
Loading "tasks.js" tasks...OK
+ yslow

Running tasks: yslow

Running "yslow" task

Running "yslow:pages" (yslow) task
Verifying property yslow.pages exists in config...OK
Files: [no src]
Files: [no src]
Options: thresholds={"weight":180,"speed":1000,"score":80,"requests":15}
>> Testing 2 URLs, this might take a few moments...
Fatal error: Unexpected end of input
```

Am using:

```
grunt-cli v0.1.13
grunt v0.4.2
node v0.10.23
```

**Comment by andyshora** [comment]
Hi Greg, thanks for this. Investigating now...

**Comment by andyshora** [comment]
I've just installed from scratch and I'm afraid I can't replicate this one. Can you please confirm you're using version 0.0.2?

I'll add some more logging in the next release for sure.

**Comment by grega** [comment]
Hi Andy, no problem. Yep sorry I'm indeed using 0.0.2.

It's odd - I'll keep playing and see if I can figure it out!

**Comment by andyshora** [comment]
I do get the 'Files: [no src]' warning, which I will fix.

However I don't get the 'Fatal error: Unexpected end of input' error. I'll look into this, it's perhaps something to do with PhantomJS.

**Comment by grega** [comment]
I tried it in a fresh project with a new Gruntfile (just in case I was getting conflicts with other tasks) and it's still outputting the same error. Stuck a bunch of log outputs into your yslow task and everything is looking good - the files objects & their properties all look fine. Shall continue investigating.

**Comment by grega** [comment]
Ok all fixed :) As you alluded to, it was an issue with PhantomJS. The following resolved the issue:

`brew update && brew install phantomjs`

**Comment by danielmatthew** [comment]
Hi @andyshora, 

Did you get anywhere with the `Files: [no src]` error, or can offer any pointers as to avoiding it? I've got `0.0.4` installed and I'm afraid I'm running into the same issue.

Current config looking like:

``` js
    yslow: {
      pages: {
        files: [{
          src: 'http://bbc.co.uk',
        }],
        options: {
          thresholds: {
            weight: 500,
            speed: 5000,
            score: 90,
            requests: 15
          }
        }
      }
    },
```

That outputs as:

``` bash
Running "yslow:pages" (yslow) task
Verifying property yslow.pages exists in config...OK
Files: [no src]
Options: thresholds={"weight":500,"speed":5000,"score":90,"requests":15}
>> Testing 1 URLs, this might take a few moments...
```

Cheers!

**Comment by danielmatthew** [comment]
Right, schoolboy error on my part: `phantomjs` wasn't installed globally, as it states at the top of the readme. My bad.

Carry on! :+1:
